# Generated by Django 4.2.6 on 2023-11-06 04:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0004_alter_doctor_colegiado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('idConsulta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_consulta', models.DateTimeField(default=django.utils.timezone.now)),
                ('razon_visita', models.TextField()),
                ('diagnostico', models.TextField()),
                ('receta', models.TextField()),
                ('estado_consulta', models.CharField(default='1', max_length=1)),
                ('idDoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.doctor')),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.paciente')),
            ],
            options={
                'db_table': 'tbconsultas',
            },
        ),
    ]
