# Generated by Django 4.2.6 on 2023-11-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('idAdmin', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=128)),
                ('role', models.CharField(default='1', max_length=1)),
            ],
            options={
                'db_table': 'tbadmin',
            },
        ),
    ]
