# Generated by Django 4.2.6 on 2023-11-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='usuario',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='usuario',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='usuario',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
