# Generated by Django 4.2.6 on 2023-11-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_alter_admin_usuario_alter_doctor_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='colegiado',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
